_target_: sbto.sim.sim_mj_rollout.SimMjRollout
cfg:
  _target_: sbto.sim.sim_mj_rollout.ConfigMjRollout
  T: 500  # will be overridden by the reference time
  step_knots: 25
  interp_kind: "pchip"
  Nthread: -1
  _chunk_size: 32
scaling:
  _target_: sbto.sim.action_scaling.Scaling
  name: nominal
  clip: False
